# Generated by Django 4.2 on 2026-04-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restock',
            name='cost_per_unit',
        ),
    ]
